# Generated by Django 4.2.13 on 2024-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_course_alter_payment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, help_text='Введите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, help_text='Введите идентификатор сессии', max_length=255, null=True, verbose_name='Идентификатор сессии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Card', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
