# Generated by Django 4.2.13 on 2024-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_link_payment_session_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма платежа'),
        ),
    ]
