# Generated by Django 4.2.13 on 2024-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Идентификатор продукта для API Stripe', max_length=255, null=True, verbose_name='Идентификатор продукта для API Stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Идентификатор продукта для API Stripe', max_length=255, null=True, verbose_name='Идентификатор продукта для API Stripe'),
        ),
    ]
