# Generated by Django 4.2.13 on 2024-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_course_stripe_product_id_lesson_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Цена курса в рублях', max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Цена урока в рублях', max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
